[package]
name = "clairvoy-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
clairvoy-core = { path = "../clairvoy-core" }
clairvoy-scanner = { path = "../clairvoy-scanner" }
clairvoy-plugins = { path = "../clairvoy-plugins" }
serde_json = "1.0"

[dev-dependencies]
tempfile = "3"
