"""
Clairvoy Command Line Interface
Local-first AI storage deduplication engine.
"""

import argparse
import sys
from pathlib import Path

from clairvoy.core.config import (
    DEFAULT_NUM_WORKERS,
    DEFAULT_SIMILARITY_THRESHOLD,
    VERSION,
)
from clairvoy.core.security import SecurityError, resolve_safe_paths
from clairvoy.engines.quarantine import QuarantineEngine
from clairvoy.engines.storage_engine import StorageEngine


def print_banner() -> None:
    banner = rf"""
   _____ _       _
  / ____| |     (_)
 | |    | | __ _ _ _ ____   _____  _   _
 | |    | |/ _` | | '__\ \ / / _ \| | | |
 | |____| | (_| | | |   \ V / (_) | |_| |
  \_____|_|\__,_|_|_|    \_/ \___/ \__, |
                                    __/ |
  Local-First AI Deduplication Engine|___/  v{VERSION}
"""
    print(banner)


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="clairvoy",
        description="Clairvoy: Local-First AI Storage Deduplication Engine",
    )
    parser.add_argument(
        "--version",
        "-v",
        action="version",
        version=f"clairvoy {VERSION}",
    )

    subparsers = parser.add_subparsers(dest="command", help="Available subcommands")

    # --- Scan Command ---
    scan_parser = subparsers.add_parser(
        "scan", help="Scan one or more directories for exact and visual near-duplicate files"
    )
    scan_parser.add_argument("paths", nargs="+", help="One or more directory paths to scan")
    scan_parser.add_argument(
        "--output",
        "-o",
        default=None,
        help="Directory to save report files (default: <first_target>/_dedupe_reports)",
    )
    scan_parser.add_argument(
        "--no-ml",
        action="store_true",
        help="Disable Vision AI model and only run exact hash deduplication",
    )
    scan_parser.add_argument(
        "--threshold",
        "-t",
        type=float,
        default=DEFAULT_SIMILARITY_THRESHOLD,
        help=f"Visual similarity threshold between 0.70 and 0.99 (default: {DEFAULT_SIMILARITY_THRESHOLD})",
    )
    scan_parser.add_argument(
        "--workers",
        "-w",
        type=int,
        default=DEFAULT_NUM_WORKERS,
        help=f"Number of parallel worker threads for I/O and hashing (default: {DEFAULT_NUM_WORKERS})",
    )

    # --- UI Command ---
    ui_parser = subparsers.add_parser(
        "ui", help="Launch the local interactive Web Application dashboard"
    )
    ui_parser.add_argument(
        "--port",
        "-p",
        type=int,
        default=8000,
        help="Web server port (default: 8000)",
    )
    ui_parser.add_argument(
        "--host",
        default="127.0.0.1",
        help="Web server host binding (default: 127.0.0.1)",
    )

    # --- Quarantine Command ---
    quarantine_parser = subparsers.add_parser(
        "quarantine", help="Safely move duplicates to quarantine using a summary report"
    )
    quarantine_parser.add_argument(
        "report_file",
        help="Path to duplicates_summary.json generated by scan",
    )
    quarantine_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview files that would be moved without actually moving them",
    )

    # --- Restore Command ---
    restore_parser = subparsers.add_parser(
        "restore", help="Restore quarantined files back to their original locations"
    )
    restore_parser.add_argument(
        "manifest_file",
        help="Path to quarantine_manifest.json created during quarantine",
    )
    restore_parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Preview files that would be restored without moving them",
    )

    args = parser.parse_args()

    if not args.command:
        print_banner()
        parser.print_help()
        sys.exit(0)

    if args.command == "scan":
        print_banner()
        try:
            target_paths = resolve_safe_paths(args.paths, must_exist=True)
            for tp in target_paths:
                if not tp.is_dir():
                    print(f"[!] Error: Path '{tp}' is not a directory.")
                    sys.exit(1)
        except (SecurityError, FileNotFoundError) as e:
            print(f"[!] Path Error: {e}")
            sys.exit(1)

        engine = StorageEngine(
            paths=target_paths,
            output_dir=args.output,
            enable_ml=not args.no_ml,
            ml_threshold=args.threshold,
            num_workers=args.workers,
        )
        engine.run()

    elif args.command == "ui":
        print_banner()
        print(f"[*] Starting Clairvoy Web Server at http://{args.host}:{args.port} ...")
        print("[*] Press Ctrl+C to terminate.")
        try:
            import uvicorn

            from clairvoy.web.app import app

            uvicorn.run(app, host=args.host, port=args.port, log_level="warning")
        except ImportError:
            print("[!] Error: Web server dependencies missing.")
            print("[*] Install with: pip install fastapi uvicorn")
            sys.exit(1)

    elif args.command == "quarantine":
        print_banner()
        report_path = Path(args.report_file).resolve()
        if not report_path.is_file():
            print(f"[!] Error: Report file '{report_path}' not found.")
            sys.exit(1)

        print(f"[*] Executing safe quarantine from: {report_path}")
        if args.dry_run:
            print("[*] DRY RUN MODE: No files will be moved.")

        manifest = QuarantineEngine.execute(report_path, dry_run=args.dry_run)
        print(f"[✓] Completed: {manifest.total_files_moved} duplicate files processed.")
        print(f" • Total Space Quarantined: {round(manifest.total_bytes_moved / (1024*1024), 2)} MB")
        print(f" • Quarantine Directory: {manifest.quarantine_dir}")

    elif args.command == "restore":
        print_banner()
        manifest_path = Path(args.manifest_file).resolve()
        if not manifest_path.is_file():
            print(f"[!] Error: Manifest file '{manifest_path}' not found.")
            sys.exit(1)

        print(f"[*] Restoring files from manifest: {manifest_path}")
        if args.dry_run:
            print("[*] DRY RUN MODE: No files will be moved.")

        count = QuarantineEngine.restore(manifest_path, dry_run=args.dry_run)
        print(f"[✓] Restored {count} files back to their original locations.")


if __name__ == "__main__":
    main()
